#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
This script allows you to sniff the Wi-Fi probe requests
passing near your wireless interface.
"""

from argparse import ArgumentParser, FileType
from csv import writer
from netaddr import EUI, NotRegisteredError
from os import geteuid
from queue import Queue, Empty
from re import compile, match, IGNORECASE
from scapy.all import *
from sys import argv, exit
from threading import Thread, Event
from time import sleep

class ProbeRequest:
    """
    A Wi-Fi probe request.
    """

    def __init__(self, timestamp, s_mac, s_mac_oui, essid):
        self.timestamp = timestamp
        self.s_mac = s_mac
        self.s_mac_oui = s_mac_oui
        self.essid = essid

class ProbeRequestSniffer:
    """
    A Wi-Fi probe request sniffer.
    """

    def __init__(self, interface, filters, display_func=lambda p: None, storage_func=lambda p: None):
        if not hasattr(display_func, '__call__'):
            raise TypeError('The display function parameter is not a callable object')
        if not hasattr(storage_func, '__call__'):
            raise TypeError('The storage function parameter is not a callable object')

        self.interface = interface
        self.filters = filters
        self.display_func = display_func
        self.storage_func = storage_func

        self.new_packets = Queue()

        self.sniffer = self.PacketSniffer(
            self.new_packets,
            self.interface,
            self.filters
        )

        self.parser = self.ProbeRequestParser(
            self.new_packets,
            self.display_func,
            self.storage_func
        )

    def start(self):
        """
        Start the sniffer.
        """

        self.sniffer.start()
        self.parser.start()

    def stop(self):
        """
        Stop the sniffer.
        """

        self.sniffer.join()
        self.parser.join()

    class PacketSniffer(Thread):
        """
        A packet sniffer.
        """

        def __init__(self, new_packets, interface, filters):
            super().__init__()

            self.new_packets = new_packets
            self.interface = interface
            self.filters = filters

            self.stop_sniffer = Event()

        def run(self):
            sniff(
                iface=self.interface,
                filter=self.filters,
                store=False,
                prn=self.new_packet,
                stop_callback=self.stop_sniffer.isSet
            )

        def join(self, timeout=None):
            """
            Stop the sniffer.
            """

            self.stop_sniffer.set()
            super().join(timeout)

        def new_packet(self, packet):
            """
            Add a new packet to the queue to be processed.
            """

            self.new_packets.put(packet)

    class ProbeRequestParser(Thread):
        """
        A Wi-Fi probe request parser.
        """

        def __init__(self, new_packets, display_func, storage_func):
            super().__init__()

            self.new_packets = new_packets
            self.display_func = display_func
            self.storage_func = storage_func

            self.stop_parser = Event()

        def run(self):
            while not self.stop_parser.isSet():
                try:
                    packet = self.new_packets.get(timeout=1)
                    probe_request = self.parse(packet)

                    if not probe_request.essid:
                        continue

                    self.display_func(probe_request)
                    self.storage_func(probe_request)

                    self.new_packets.task_done()
                except Empty:
                    pass

        def join(self, timeout=None):
            """
            Stop the current thread.
            """

            self.stop_parser.set()
            super().join(timeout)

        def parse(self, packet):
            """
            Parse the packet and return a probe request object.
            """

            timestamp = packet.getlayer(RadioTap).time
            s_mac = packet.getlayer(RadioTap).addr2
            s_mac_oui = self.get_mac_organisation(s_mac)
            essid = packet.getlayer(Dot11ProbeReq).info.decode("utf-8")

            return ProbeRequest(timestamp, s_mac, s_mac_oui, essid)

        def get_mac_organisation(self, mac):
            """
            Returns the OUI of a MAC address as a string.
            """

            try:
                return EUI(mac).oui.registration().org
            except NotRegisteredError:
                return None

if __name__ == "__main__":
    ap = ArgumentParser(description="Wi-Fi Probe Requests Sniffer")
    essid_arguments = ap.add_mutually_exclusive_group()

    essid_arguments.add_argument("-e", "--essid", nargs="+", help="ESSID of the APs to filter (space-separated list)")
    ap.add_argument("--exclude", nargs="+", help="MAC addresses of the stations to exclude (space-separated list)")
    ap.add_argument("-i", "--interface", required=True, help="wireless interface to use (must be in monitor mode)")
    ap.add_argument("--ignore-case", action="store_true", help="ignore case distinctions in the regex pattern (default: false)")
    ap.add_argument("-o", "--output", type=FileType("a"), help="output file to save the captured data (CSV format)")
    essid_arguments.add_argument("-r", "--regex", help="regex to filter the ESSIDs")
    ap.add_argument("-s", "--station", nargs="+", help="MAC addresses of the stations to filter (space-separated list)")

    ap.set_defaults(ignore_case=False)
    args = vars(ap.parse_args())

    if not geteuid() == 0:
        exit("[!] You must be root")

    if args["output"]:
        outfile = writer(args["output"], delimiter=";")

    if args["essid"]:
        essid_filter = args["essid"]

    if args["regex"]:
        if args["ignore_case"]:
            essid_regex = compile(args["regex"], IGNORECASE)
        else:
            essid_regex = compile(args["regex"])

    filters = "type mgt subtype probe-req"

    if args["exclude"]:
        filters += " and not ("

        for i, station in enumerate(args["exclude"]):
            if i == 0:
                filters += "ether src host {s_mac}".format(s_mac=station)
            else:
                filters += " || ether src host {s_mac}".format(s_mac=station)

        filters += ")"

    if args["station"]:
        filters += " and ("

        for i, station in enumerate(args["station"]):
            if i == 0:
                filters += "ether src host {s_mac}".format(s_mac=station)
            else:
                filters += " || ether src host {s_mac}".format(s_mac=station)

        filters += ")"

    def display_func(probe_request):
        print("{timestamp} - {s_mac} ({mac_org}) -> {essid}".format(
            timestamp=probe_request.timestamp,
            s_mac=probe_request.s_mac,
            mac_org=probe_request.s_mac_oui,
            essid=probe_request.essid
        ))

    print("[*] Start sniffing probe requests...")

    try:
        sniffer = ProbeRequestSniffer(
            args["interface"],
            filters,
            display_func
        )

        sniffer.start()

        while True:
            sleep(100)
    except IOError:
        exit("[!] Interface doesn't exist")
    except KeyboardInterrupt:
        print("[*] Stopping the threads...")
        sniffer.stop()
        print("[*] Bye!")
